# general settings
name: NAFNet-GoPro-width64
model_type: ImageRestorationModel
scale: 1
num_gpu: 8
manual_seed: 10

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: ../datasets/GoPro/train/target
    dataroot_lq: ../datasets/GoPro/train/input
    filename_tmpl: '{}'
    io_backend:
      type: disk
    gt_size: 256
    use_flip: true
    use_rot: true
    batch_size_per_gpu: 5
    total_iter: 640000
    use_shuffle: true
    num_worker_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: ../datasets/GoPro/test/target.lmdb
    dataroot_lq: ../datasets/GoPro/test/input.lmdb
    io_backend:
      type: lmdb
    val_freq: 10000

network_g:
  type: v51editLocal
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  best_state: experiments/NAFNet-GoPro-width64/best_model.pth

# training settings
train:
  train:
    mixup: false
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: !!float 1e-8
    # clip_grid_norm: 0.1  # 已移除无效参数
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 640000
    eta_min: !!float 1e-7

  total_iter: 640000
  warmup_iter: -1

  losses:
    pixel:
      type: SmoothL1Loss
      loss_weight: 0.5
    perceptual:
      type: PerceptualLoss
      layer_name: 'relu3_3'
      vgg_type: 'vgg19'
      criterion: 'l1'

# validation settings
val:
  val_freq: !!float 10000
  save_img: false
  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500