# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: v51_fft-GoPro-width64
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 10 

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: /home/user/NAFNet/datasets/GoPro/train/target
    dataroot_lq: /home/user/NAFNet/datasets/GoPro/train/input

    filename_tmpl: '{}'
    io_backend:
      type: disk #lmdb

    gt_size: 128  #256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 6
    dataset_enlarge_ratio: 1
    transforms:
        - ['AdjustSize', {'patch_size': 16}]      # 先调整尺寸
        - ['PairedRandomCrop', {'gt_patch_size': 128, 'scale': 1}]
        - ['Augment', {'hflip': True, 'rotation': True}]
    phase: train
    scale: 1
    prefetch_mode: ~
    accumulation_steps: 4  # 梯度累积步数
    use_grad_clip: true    # 启用梯度裁剪
    use_amp: true          # 启用混合精度


  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: /home/user/NAFNet/datasets/GoPro/test/target.lmdb
    dataroot_lq: /home/user/NAFNet/datasets/GoPro/test/input.lmdb
    io_backend:
      type: lmdb
    transforms:
      - [Resize, {'size': [128, 128]}]
    phase: val
    scale: 1


network_g:
  type: v51fftLocal
  width: 48  #64
  enc_blk_nums: [2, 2, 3, 6]  #[1, 1, 1, 28]
  middle_blk_num: 2
  dec_blk_nums: [4, 2, 1, 1]
  patch_size: 8
  denoising_config:
    enable_layers: [1, 2, 3]  # 跳过第一层（保留底层细节）
    type: "adaptive"         # 自适应强度去噪
    depth_aware: true        # 随深度增加去噪强度

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1.5e-4 #1e-3
    weight_decay: !!float 5e-5 #1e-3
    betas: [0.9,0.999] #[0.9, 0.9]

  # scheduler:
  #   type: TrueCosineAnnealingLR
  #   T_max: 400000
  #   eta_min: !!float 1e-7
  # 学习率调度
  scheduler:
    type: CosineAnnealingWarmRestarts
    T_0: 10             # 重启周期
    T_mult: 2  # 周期倍增系数
    eta_min: !!float 1e-6    # 最小学习率

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss #PSNRLoss
    loss_weight: 0.6

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.7

  perceptual_loss_opt:
    type: PerceptualLoss
    loss_weight: 0.15 #1
    use_vgg: 'vgg11'
    layers: ['3', '8']
  
  # 新增SSIM Loss配置
  ssim_loss_opt:
    type: SSIMLoss
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 1e6
  save_img: true


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 400
  save_checkpoint_freq: !!float 8e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29990

# 系统优化
amp: true                 # 启用混合精度
accumulation_steps: 4     # 等效batch_size=16