# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: v51_fft-GoPro-width64
model_type: ImageRestorationModel
scale: 1
num_gpu: 4
manual_seed: 10 

datasets:
  train:
    name: gopro-train
    type: PairedImageDataset
    dataroot_gt: /home/user/NAFNet/datasets/GoPro/train/target
    dataroot_lq: /home/user/NAFNet/datasets/GoPro/train/input

    filename_tmpl: '{}'
    io_backend:
      type: disk #lmdb

    gt_size: 128  #256
    use_flip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 1
    prefetch_mode: ~


  val:
    name: gopro-test
    type: PairedImageDataset
    dataroot_gt: /home/user/NAFNet/datasets/GoPro/test/target.lmdb
    dataroot_lq: /home/user/NAFNet/datasets/GoPro/test/input.lmdb
    io_backend:
      type: lmdb


network_g:
  type: v51fftLocal
  width: 64  #64
  enc_blk_nums: [1, 1, 1, 28]  #[1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]
  patch_size: 8 # 新增 patch_size 参数

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 400000
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: L1Loss #PSNRLoss
    loss_weight: 1.0 #1
    reduction: mean

  fft_loss_opt:
    type: FFTLoss
    loss_weight: 0.5 #1
    reduction: mean

  perceptual_loss_opt:
    type: PerceptualLoss
    loss_weight: 0.05 #1
    reduction: mean
    use_l1_loss: false 
    feature_extract_layers: ['3', '8', '15', '22']  # 定义提取特征的层编号
    vgg_type: vgg19
  
  # 新增SSIM Loss配置
  ssim_loss_opt:
    type: SSIMLoss
    loss_weight: 0.1
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e6
  save_img: true


  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 400
  save_checkpoint_freq: !!float 8e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29990